### ISSUE TITLE
outdated dependancies

### ISSUE THREAD

**Issue by Vanderscycle** [sveltech/routify-guide-example#21]
Hi,

I am following this example from routify.dev and keep getting an error during runtime.
```js
import { config } from '@sveltech/routify'
```
looking at routify it seems that @sveltech/routify is not [supported anymore](https://routify.dev/blog/routify-2). What do you recommend using?

**Comment by Vanderscycle** [comment]
Actually, is this example still supported or is this other [example repo](https://github.com/roxiness/routify-starter/issues) is now the most up-to-date reference? If so I recommend archiving this example.

Thanks,

**Comment by jakobrosenberg** [comment]
Thanks for pointing this out. This repo was intended for a tutorial where each branch was a small chapter. Alas the repo got finished, but the tutorial didn't.

I'm not sure if we should update the repo or archive it. @ghostdevv ?

**Comment by ghostdevv** [comment]
@jakobrosenberg Probably archive this now;

@Vanderscycle check out https://www.npmjs.com/package/stackmix
